(function() {
/* Copyright 2008 Google Inc. */

if(!("google"in window)){window.google={}}if(!("earth"in window.google)){window.google.earth={}};if(!("google"in window)){window.google={}}if(!("idlglue"in window.google)){window.google.idlglue={}}window.google.idlglue.BROWSER_FIREFOX="ff";window.google.idlglue.BROWSER_IE="ie";window.google.idlglue.BROWSER_MOZILLA="moz";window.google.idlglue.BROWSER_OPERA="opera";window.google.idlglue.BROWSER_NETSCAPE="netscape";window.google.idlglue.BROWSER_CHROME="chrome";window.google.idlglue.BROWSER_SAFARI="safari";window.google.idlglue.supportsNpapi=function(a){var c=window.google.idlglue;return a==c.BROWSER_FIREFOX||
a==c.BROWSER_MOZILLA||a==c.BROWSER_NETSCAPE||a==c.BROWSER_CHROME||a==c.BROWSER_OPERA||a==c.BROWSER_SAFARI};window.google.idlglue.PLATFORM_MAC="mac";window.google.idlglue.PLATFORM_LINUX="linux";window.google.idlglue.PLATFORM_WINDOWS="windows";window.google.idlglue.PLUGIN_MAIN_CLSID="F9152AEC-3462-4632-8087-EEE3C3CDDA24";window.google.idlglue.PLUGIN_MAIN_MIMETYPE="application/geplugin";window.google.idlglue.findAvailableId=function(a){var c=null;for(var d=0;d<100;d++){var e=a+d;if(!document.getElementById(e)){c=
e}}return c};window.google.idlglue.getPlatform=function(){var a=navigator.userAgent;if(a.indexOf("Windows")>=0){return window.google.idlglue.PLATFORM_WINDOWS}if(a.indexOf("Macintosh")>=0){return window.google.idlglue.PLATFORM_MAC}if(a.indexOf("Linux")>=0){return window.google.idlglue.PLATFORM_LINUX}return null};window.google.idlglue.getBrowser=function(){var a=navigator.appName,c=navigator.userAgent,d=window.google.idlglue,e=d.getPlatform();if(c.indexOf("Opera")>=0){return d.BROWSER_OPERA}else if(c.indexOf("Firefox")>=
0||c.indexOf("Minefield")>=0){return d.BROWSER_FIREFOX}else if(c.indexOf("Chrome")>=0){return d.BROWSER_CHROME}else if(c.indexOf("Safari")>=0){return d.BROWSER_SAFARI}else if(a.indexOf("Internet Explorer")>=0){return d.BROWSER_IE}else if(a.indexOf("Mozilla")>=0){return d.BROWSER_MOZILLA}else if(a.indexOf("Netscape")>=0){return d.BROWSER_NETSCAPE}return null};window.google.idlglue.getIsIe6=function(){var a=navigator.userAgent;if(a.indexOf("MSIE 6.0;")>=0){return true}return false};window.google.idlglue.getIeMajorVersion=
function(){var a=navigator.userAgent,c=a.indexOf("MSIE ");if(c==-1){return 0}else{return parseInt(a.substring(c+5,a.indexOf(";",c)),10)}};window.google.idlglue.isSupportedPlatform=function(a){var c=window.google.idlglue;return a==c.PLATFORM_WINDOWS||a==c.PLATFORM_MAC};window.google.idlglue.isSupportedBrowser=function(a,c){var d=window.google.idlglue;if(a==d.PLATFORM_WINDOWS){return c==d.BROWSER_FIREFOX||c==d.BROWSER_IE&&d.getIeMajorVersion()<9||c==d.BROWSER_CHROME||c==d.BROWSER_MOZILLA||c==d.BROWSER_NETSCAPE}else if(a==
d.PLATFORM_MAC){return c==d.BROWSER_FIREFOX||c==d.BROWSER_SAFARI||c==d.BROWSER_CHROME}else if(a==d.PLATFORM_LINUX){return c==d.BROWSER_FIREFOX||c==d.BROWSER_MOZILLA}return false};window.google.idlglue.isSupported=function(){var a={},c=document.location.hash.replace(/(^#)/,""),d=c.split("&");for(var e=0;e<d.length;e++){var f=d[e].split("="),b=undefined;if(f.length>1){b=decodeURIComponent(f[1])}a[decodeURIComponent(f[0])]=b}var h="geplugin_browserok";if(h in a){if(a[h]=="0"||a[h]=="false"){return false}else{return true}}var g=
window.google.idlglue,j=g.getPlatform(),i=g.getBrowser();if(g.isSupportedPlatform(j)&&g.isSupportedBrowser(j,i)){return true}return false};window.google.idlglue.logCsi=function(a,c,d,e){if(d.length){var f="";for(var b=0;b<d.length;b++){var h=d[b];if(b>0){f+=","}f+=h[0]+"."+h[1]}var g="http://csi.gstatic.com/csi";if(window.location.protocol=="https:"){g="https://www.google.com/csi"}var j=g+"?v=2&s="+a+"&rls="+c+"&it="+f;if(e){j+="&"+e}window.google.idlglue.createImageForLogging(j)}};window.google.idlglue.createImageForLogging=
function(a){var c=new Image,d=window.google.idlglue.createImageForLogging.m++;window.google.idlglue.createImageForLogging.f[d]=c;c.onload=(c.onerror=function(){delete window.google.idlglue.createImageForLogging.f[d]});c.src=a;c=null};window.google.idlglue.createImageForLogging.f={};window.google.idlglue.createImageForLogging.m=0;window.google.idlglue.showError=function(a,c,d){var e=window.google.idlglue;a.pluginDiv.style.left=""+-screen.width*2+"px";a.pluginDiv.style.top=""+-screen.height*2+"px";
a.messageDiv.style.display="";var f="";if(d){f="&detail="+encodeURIComponent(d)}a.messageDiv.innerHTML='<iframe src="'+a.errorUrl+"#error="+encodeURIComponent(c)+f+'" width="100%" height="100%" frameborder=0></iframe>';e.doErrorCleanup(a)};window.google.idlglue.doErrorCleanup=function(a){var c=a.errorCleanupCallbacks;if(c){for(var d=0;d<c.length;d++){c[d]()}a.errorCleanupCallbacks=null}if(a.pluginDiv.parentNode==a.positioningDiv){a.positioningDiv.removeChild(a.pluginDiv)}a.iface=null;a.div=null;a.pluginDiv=
null};window.google.idlglue.createPluginAsInnerHTML=function(a,c,d){var e=window.google.idlglue;if(window.google.idlglue.supportsNpapi(a)){c.innerHTML='<embed type="'+e.PLUGIN_MAIN_MIMETYPE+'" style="margin:0px; padding:0px; width:100%; height:100%;"></embed>';return true}else if(a==e.BROWSER_IE){c.innerHTML='<object id="'+d+'" classid="CLSID:'+e.PLUGIN_MAIN_CLSID+'" style="margin:0px; padding:0px; width:100%; height:100%;"></object>';return true}c.innerHTML="<div></div>";return false};window.google.idlglue.addErrorCleanupCallback=
function(a,c){if(!a.errorCleanupCallbacks){a.errorCleanupCallbacks=[]}a.errorCleanupCallbacks.push(c)};window.google.idlglue.create=function(a,c,d,e){var f=window.google.idlglue;e=e||{};var b=f.getBrowser(),h=f.getPlatform(),g=f.isSupported(),j=(new Date).getTime(),i=document.createElement("div");i.style.position="relative";i.style.width="100%";i.style.height="100%";i.style.overflow="hidden";a.appendChild(i);if(h==f.PLATFORM_MAC){var k=document.createElement("div");k.style.position="absolute";k.style.width=
"100%";k.style.height="100%";k.style.background="#FFF";i.appendChild(k)}var m=document.createElement("div"),n=m.style;n.position="relative";n.width="100%";n.height="100%";n.background="#E5E3DF url("+window.google.earth.k+") no-repeat scroll 50% 50%";i.appendChild(m);var o=document.createElement("div");n=o.style;n.position="relative";n.left=""+-screen.width*2+"px";n.top=""+-screen.height*2+"px";n.width="100%";n.height="100%";i.appendChild(o);var l={};l.div=o;l.pluginDiv=o;l.divInner=o;l.topDiv=a;l.positioningDiv=
i;l.messageDiv=m;l.platform=h;l.browser=b;l.errorUrl=d;l.startLoadingTime=j;var p=f.findAvailableId("__idlglue_plugin__");if(!p){f.showError(l,"ERR_NO_AVAILABLE_ID","");return null}l.pluginId=p;o.id="_idlglue_pluginDiv_"+p;if(g&&!f.isInstalled()){if(e.skipDownloadButton){if(e.autoDownload==undefined||e.autoDownload){f.showError(l,"INSTALLING","")}else{f.showError(l,"VIEW_INSTALLING","")}}else{f.showError(l,"ERR_NOT_INSTALLED","")}c(null);return}if(!g&&(!h||!f.isSupportedPlatform(h))){f.showError(l,
"ERR_UNSUPPORTED_PLATFORM","");c(null);return}if(!g||!f.createPluginAsInnerHTML(b,o,p)){f.showError(l,"ERR_UNSUPPORTED_BROWSER","");c(null);return}var s=function(q,v){window.setTimeout(function(){q.iface=v.firstChild;if(!("getSelf"in q.iface)){f.showError(q,"ERR_CREATE_PLUGIN","");c(null)}else{c(q)}},1)};s(l,o)};window.google.idlglue.getPluginContainerNode=function(a){if(!a||!("getDiv_"in a)){return null}var c=a.getDiv_();return c.parentNode.parentNode};window.google.idlglue.isInstalled=function(){try{var a=
window.google.idlglue,c=a.getBrowser();if(window.google.idlglue.supportsNpapi(c)){var d=navigator.mimeTypes[a.PLUGIN_MAIN_MIMETYPE];if(d&&d.enabledPlugin){return true}}else if(c==a.BROWSER_IE){var e=document.createElement("div"),f=a.findAvailableId("isInstalled_test");if(a.createPluginAsInnerHTML(c,e,f)){return e.firstChild.getSelf()!=null}}}catch(b){}return false};window.google.earth.ErrorCode={ERR_OK:"ERR_OK",ERR_DESTROYED:"ERR_DESTROYED",ERR_CREATE_PLUGIN:"ERR_CREATE_PLUGIN",ERR_INVALID_DIV:"ERR_INVALID_DIV",ERR_NO_AVAILABLE_ID:"ERR_NO_AVAILABLE_ID",ERR_UNSUPPORTED_BROWSER:"ERR_UNSUPPORTED_BROWSER",ERR_UNSUPPORTED_PLATFORM:"ERR_UNSUPPORTED_PLATFORM",ERR_MAX_EARTH_PROCESSES:"ERR_MAX_EARTH_PROCESSES",ERR_SHUTOFF:"ERR_SHUTOFF",ERR_NOT_INSTALLED:"ERR_NOT_INSTALLED",ERR_INIT:"ERR_INIT",ERR_VERSION:"ERR_VERSION",ERR_API_KEY:"ERR_API_KEY",ERR_EARTH_NOT_READY:"ERR_EARTH_NOT_READY",
ERR_BRIDGE:"ERR_BRIDGE",ERR_CREATE_EARTH:"ERR_CREATE_EARTH",ERR_CREATE_CONNECT_MUTEX:"ERR_CREATE_CONNECT_MUTEX",ERR_EARTH_CONNECT_TIMEOUT:"ERR_EARTH_CONNECT_TIMEOUT",ERR_BRIDGE_OTHER_SIDE_PROBLEM:"ERR_BRIDGE_OTHER_SIDE_PROBLEM",ERR_BRIDGE_TIMEOUT:"ERR_BRIDGE_TIMEOUT",ERR_PLUGIN_NOT_READY:"ERR_PLUGIN_NOT_READY",ERR_BAD_URL:"ERR_BAD_URL",ERR_DATABASE_LOGIN_FAILURE:"ERR_DATABASE_LOGIN_FAILURE",ERR_INVALID_LANGUAGE:"ERR_INVALID_LANGUAGE"};window.google.earth.ErrorCodeToString={0:"ERR_OK",1:"ERR_DESTROYED",
100:"ERR_CREATE_PLUGIN",101:"ERR_INVALID_DIV",102:"ERR_NO_AVAILABLE_ID",103:"ERR_UNSUPPORTED_BROWSER",104:"ERR_UNSUPPORTED_PLATFORM",105:"ERR_MAX_EARTH_PROCESSES",106:"ERR_SHUTOFF",107:"ERR_NOT_INSTALLED",200:"ERR_INIT",201:"ERR_VERSION",202:"ERR_API_KEY",203:"ERR_EARTH_NOT_READY",300:"ERR_BRIDGE",301:"ERR_CREATE_EARTH",302:"ERR_CREATE_CONNECT_MUTEX",303:"ERR_EARTH_CONNECT_TIMEOUT",304:"ERR_BRIDGE_OTHER_SIDE_PROBLEM",305:"ERR_BRIDGE_TIMEOUT",400:"ERR_PLUGIN_NOT_READY",401:"ERR_BAD_URL",402:"ERR_DATABASE_LOGIN_FAILURE",
403:"ERR_INVALID_LANGUAGE"};(function(){function a(b,h,g,j){var i=this;i.left=b!=undefined?b:-1;i.top=h!=undefined?h:-1;i.width=g!=undefined?g:-1;i.height=j!=undefined?j:-1}function c(b){var h=b.offsetWidth,g=b.offsetHeight;if(b.getBoundingClientRect){var j=b.getBoundingClientRect(),i=j.left,k=j.top,m=b.ownerDocument;i+=Math.max(m.documentElement.scrollLeft,m.body.scrollLeft);k+=Math.max(m.documentElement.scrollTop,m.body.scrollTop);i+=-m.documentElement.clientLeft;k+=-m.documentElement.clientTop;return new a(i,k,h,g)}var i=
0,k=0;while(b){i+=b.offsetLeft;k+=b.offsetTop;try{b=b.offsetParent}catch(n){b=b.parentNode}}return new a(i,k,h,g)}function d(b){var h=false;while(b){if(b==document){return true}var g;if("getComputedStyle"in window){g=window.getComputedStyle(b,"")}else if("currentStyle"in b){g=b.currentStyle}else{g=b.style}if(g.display=="none"){return false}if(!h){if(g.visibility=="hidden"){return false}else if(g.visibility=="visible"){h=true}}b=b.parentNode}return true}f.ADDITION="addition";f.PRE_REMOVAL="pre_removal";
f.REMOVAL="removal";f.BOUNDS="bounds";f.VISIBILITY="visibility";f.GET_RECT_IN_PIXELS="get_rect_in_pixels";function e(){var b=this;b.b={}}e.prototype.c=false;e.prototype._dispatchCallback=function(b,h){var g=this;if(g.c||!g._hasCallback(b)){return null}g.c=true;try{var j=g.b[b](b,h)}catch(i){}g.c=false;return j};e.prototype._setCallback=function(b,h){if(h){this.b[b]=h}else{delete this.b[b]}};e.prototype._hasCallback=function(b){return b in this.b&&this.b[b]};function f(b,h){var g=this;g.node=b;g.rect=
new a;g.visibility=d(b);b.h="nodeObserverId_"+g.d;g.d++;g.h=b.h;if(h){g.callbacks=h}else{g.callbacks=new e}var j=250;g.i=setInterval(function(){g.j()},j)}f.prototype.d=0;f.prototype.j=function(){var b=this,h=false,g=b.node.parentNode;while(g){if(g==document){h=true;break}g=g.parentNode}if(!h){b.callbacks._dispatchCallback(f.PRE_REMOVAL,b);b.callbacks._dispatchCallback(f.REMOVAL,b);b.destroy();return}var j=false,i=false;if(b.callbacks._hasCallback(f.BOUNDS)){var k=b.rect,m;if(b.callbacks._hasCallback(f.GET_RECT_IN_PIXELS)){m=
b.callbacks._dispatchCallback(f.GET_RECT_IN_PIXELS,b)}else{m=c(b.node)}j=k.left!=m.left||k.top!=m.top||k.width!=m.width||k.height!=m.height;b.rect=m;if(j){b.callbacks._dispatchCallback(f.BOUNDS,b)}}if(b.callbacks._hasCallback(f.VISIBILITY)){var n=d(b.node),i=b.visibility!=n;b.visibility=n;if(i){b.callbacks._dispatchCallback(f.VISIBILITY,b)}}};f.prototype.destroy=function(){var b=this;if(b.i!=-1){clearInterval(b.i)}b.callbacks={}};google.idlglue.NodeObserver=f;google.idlglue.NodeObserverCallbacks=
e;google.idlglue.Rect=a;google.idlglue.getElementRect=c})();window.google.earth.g="";window.google.earth.setLanguage=function(a){window.google.earth.g=a};window.google.earth.setErrorUrl=function(a){window.google.earth.e=a};window.google.earth.setLoadingImageUrl=function(a){window.google.earth.k=a};window.google.earth.createInstance=function(a,c,d,e){var f=window.google.earth.ErrorCode,b;c=c||function(){};d=d||function(){};e=e||{};if(typeof a=="string"){b=document.getElementById(a)}else{b=a}if(!b){d(f.ERR_INVALID_DIV);return}e.language=e.language||google.earth.g;
var h=c;c=function(l){var p=l.getLayerRoot().getLayerById(l.LAYER_BORDERS);if(p){google.earth.addEventListener(p,"click",function(s){s.preventDefault()})}h(l)};var g="";try{if(e.language){g="intl/"+e.language+"/"}}catch(j){}var i="http://www.google.com/";if(window.location.protocol=="https:"){i="https://www.google.com/"}var k=i+g+"earth/plugin/error.html";if("database"in e&&typeof e.database=="string"&&window.google.earth.e){k=window.google.earth.e}var m=window.google.earth.stopIntrospectInstallation_(),
n=window.google.earth.l(f,c,d,m,e),o={skipDownloadButton:e.skipDownloadButton,autoDownload:e.autoDownload};window.google.idlglue.create(b,n,k,o)};window.google.earth.l=function(a,c,d,e,f){return function(b){if(b){var h=c;c=function(j){var i=false;google.earth.executeBatch(j,function(){i=true});if(!i){var k="SUCCESS_RECENT_INSTALL_RESTART";window.google.idlglue.showError(b,k,"event bug");d(k);return}h(j)};var g=b.iface.getJavascriptInitCode_();eval(g)(b,c,d,f);if(b.pluginDiv.logStore){b.pluginDiv.logStore.prewarmTime=
e.time;b.pluginDiv.logStore.prewarmFinished=e.finished;b.pluginDiv.logStore.didPrewarm=e.didPrewarm}}else{d(a.ERR_CREATE_PLUGIN)}}};window.google.earth.a=null;window.google.earth.introspectInstallation_=function(){if(window.google.earth.a)return;var a=document.createElement("div");a.style.cssText="visibility: hidden;position: absolute;width: 0px;height: 0px;";document.body.appendChild(a);var c=window.google.idlglue.findAvailableId("introspect-installation"),d=window.google.idlglue.getBrowser();if(window.google.idlglue.createPluginAsInnerHTML(d,
a,c)){if("getSelf"in a.firstChild){var e=a.firstChild.getSelf();if("introspectInstallation_"in e){e.introspectInstallation_();window.google.earth.a=a}}}if(!window.google.earth.a)document.body.removeChild(a)};if(document.getElementById("__maps-earth-introspect-installation__")){window.google.earth.introspectInstallation_()}window.google.earth.stopIntrospectInstallation_=function(){var a={time:-1,finished:false};if(window.google.earth.a){var c=window.google.earth.a,d=c.firstChild.getSelf();d.stopIntrospectInstallation_();
a=window.google.earth.queryIntrospectInstallation_();document.body.removeChild(c);window.google.earth.a=null}return a};window.google.earth.queryIntrospectInstallation_=function(){var a={time:-1,finished:false};if(window.google.earth.a){var c=window.google.earth.a,d=c.firstChild.getSelf();try{a.time=d.getLogValue_(4);a.finished=d.getLogValue_(3)}catch(e){a.didPrewarm=true}}return a};window.google.earth.getPluginContainerNode=window.google.idlglue.getPluginContainerNode;window.google.earth.isSupported=
window.google.idlglue.isSupported;window.google.earth.isInstalled=window.google.idlglue.isInstalled;if(window.location.protocol=="https:"){window.google.earth.setLoadingImageUrl("https://www.google.com/earth/plugin/images/loading.gif")}else{window.google.earth.setLoadingImageUrl("http://www.google.com/earth/plugin/images/loading.gif")}if(window.google.earth.LoadArgs){var t=window.google.earth.LoadArgs.split("&");for(var r=0;r<t.length;r++){if(t[r]){var u=t[r].split("=");if(u.length==2&&u[0]=="hl"){window.google.earth.setLanguage(u[1])}}}};

google.loader.loaded({"module":"earth","version":"1.0","components":["default"]});
google.loader.eval.earth = function() {eval(arguments[0]);};if (google.loader.eval.scripts && google.loader.eval.scripts['earth']) {(function() {var scripts = google.loader.eval.scripts['earth'];for (var i = 0; i < scripts.length; i++) {google.loader.eval.earth(scripts[i]);}})();google.loader.eval.scripts['earth'] = null;}})();